// <auto-generated />
using Drinks.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drinks.Migrations
{
    [DbContext(typeof(DrinksContext))]
    partial class DrinksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Drinks.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("IngredientIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientIds = "[1,5]",
                            Name = "Expresso"
                        },
                        new
                        {
                            Id = 2,
                            IngredientIds = "[1,5,5]",
                            Name = "Allongé"
                        },
                        new
                        {
                            Id = 3,
                            IngredientIds = "[1,3,5,6]",
                            Name = "Capuccino"
                        },
                        new
                        {
                            Id = 4,
                            IngredientIds = "[2,5,6,6,6,7,7]",
                            Name = "Chocolat"
                        },
                        new
                        {
                            Id = 5,
                            IngredientIds = "[5,5,4]",
                            Name = "The"
                        });
                });

            modelBuilder.Entity("Drinks.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 1.0,
                            Name = "Cafe"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 0.10000000000000001,
                            Name = "Sucre"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 0.5,
                            Name = "Creme"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 2.0,
                            Name = "The"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 0.20000000000000001,
                            Name = "Eau"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 1.0,
                            Name = "Chocolat"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 0.40000000000000002,
                            Name = "Lait"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
